services:
  - type: web
    name: my-python-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app & python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
        
